map_app/static/html/legend.html
map_app/static/js/data_processing.js

This is candidate naming, as the to/from descriptors seem to be confusing and vague. Hopefully, at the cost of making them longer, this will both correct and clarify things.
Additionally, quickly added some error prevention to the various button functions.

Reversing labels on legend for to/from layers, Input validation

---

README.md
modules/data_processing/forcings.py
modules/data_processing/gpkg_utils.py
modules/data_processing/subset.py
modules/ngiab_data_cli/__main__.py
pyproject.toml

- Adds CLI documentation to the README
- Reduces the amount of info logs 
- Adds colours to the CLI logs where visual feedback from them is more important.

Cli readme and logging

---

modules/data_processing/create_realization.py
modules/data_sources/noah-owp-modular-init.namelist.input

updates the soil type and vegetation types in the init files for noaa owp modular

Add soil type and veg type to nowpm realizations

---

README.md
modules/data_processing/gpkg_utils.py
modules/map_app/static/css/main.css
modules/map_app/static/js/main.js
modules/map_app/templates/index.html
modules/map_app/views.py
modules/ngiab_data_cli/__main__.py

- adds lat lon cli input
- adds lat lon map selection
- adds wbid map selection
- adds clear selection button to map
- suppresses "random" dask communication errors on shutdown after cli command successfully completes
- updates cli documentation to add examples

Select by wbid lat long

---

README.md
modules/data_processing/gpkg_utils.py
modules/map_app/static/js/main.js
modules/map_app/templates/index.html
modules/map_app/views.py
modules/ngiab_data_cli/__main__.py

- Adds select by gage_id to the map
- Adds -g option to cli allowing you to supply a gage_id

Add select by gage id 

---

modules/data_processing/forcings.py
modules/data_processing/zarr_utils.py
pyproject.toml

refactors forcing generation to use numpy and shared memory
something changed and the numba parallelisation stopped working so now numpy is ~20x faster

Faster forcings

---

README.md
modules/data_processing/create_realization.py
modules/data_processing/file_paths.py
modules/data_processing/forcings.py
modules/data_processing/gpkg_utils.py
modules/data_processing/graph_utils.py
modules/data_processing/subset.py
modules/map_app/__main__.py
modules/map_app/static/css/colors.css
modules/map_app/static/css/legend.css
modules/map_app/static/css/map.css
modules/map_app/static/html/legend.html
modules/map_app/static/js/data_processing.js
modules/map_app/static/js/legend.js
modules/map_app/static/js/main.js
modules/map_app/templates/index.html
modules/map_app/views.py
modules/ngiab_data_cli/__main__.py

Changes from waterbody to catchment orientated delineation. mostly what has changed id that wb is replaced with cat, and now upstream catchments are calculated from the outflow of the catchment rather than the inflow.
more details here https://github.com/CIROH-UA/NGIAB_data_preprocess/releases/tag/v2.0.0-beta
* Additionally running the cli using gage id will name the output folder after the gage to make it clearer what command generated that folder.
* Fixed an issue where the cli would create an additional dask client rather than fetching the existing one.

Outflow delineation

---

modules/data_processing/gpkg_utils.py
modules/ngiab_data_cli/__main__.py
pyproject.toml

Compares two sources of gage to catchment mappings in the geopackage to resolve issues where a gage is associated to multiple waterbodies and or nexuses 
Bump geopandas minimum version to 1.0.0 to remove fiona dependency

Gage crosswalk

---

README.md
modules/data_processing/create_realization.py
modules/data_processing/file_paths.py
modules/data_processing/forcings.py
modules/data_processing/gpkg_utils.py
modules/data_processing/graph_utils.py
modules/data_processing/subset.py
modules/data_processing/zarr_utils.py
modules/data_sources/source_validation.py
modules/map_app/__main__.py
modules/map_app/views.py
modules/ngiab_data_cli/__main__.py
modules/ngiab_data_cli/arguments.py
modules/ngiab_data_cli/custom_logging.py
pyproject.toml

- removes csv input (it wasn't functioning as needed)
- refactors cli validation and workflow dependencies to be clearer and less error prone
- refactors file_paths to use attributes and properties to allow `file_paths.conus_hydrofabric` syntax not requiring the () function brackets

Cli refactor

---

modules/data_processing/create_realization.py
modules/data_processing/file_paths.py
modules/data_processing/gpkg_utils.py
modules/data_processing/subset.py
modules/data_processing/zarr_utils.py
modules/data_sources/cfe-template.ini
modules/data_sources/ngen-routing-template.yaml
modules/ngiab_data_cli/__main__.py

- refactor the catchment model initialization to use templates rather than loading and saving yaml or json; to preserve comments
- update cli logged output folder to be a hyperlink so you can click it to open the folder
- calculate CFE's groundwater storage initial state based on the national water model output for a given catchment and time (without this, a up to a few years of simulation needed to be run for the gw_storage to reach equilibrium)

Realization rework

---

README.md
modules/data_processing/file_paths.py
modules/data_processing/forcings.py
modules/data_processing/gpkg_utils.py
modules/data_processing/graph_utils.py
modules/data_processing/subset.py
modules/ngiab_data_cli/__main__.py
modules/ngiab_data_cli/arguments.py

adds vpu subsetting
`--vpu 01` instead of `-i cat 12345` to get all of vpu 01

Vpu subset

---

modules/data_processing/create_realization.py
modules/data_sources/noah-owp-modular-init.namelist.input

fixes slope parameter and lat / lng units
#72

Parameter fixes

---

.gitignore
modules/data_processing/forcings.py
modules/data_processing/zarr_utils.py
modules/ngiab_data_cli/forcing_cli.py
pyproject.toml

adds an independent cli just for generating forcings
this is not the best way of doing this and will need to be revisited when aorc forcing input is added

added independant forcing cli

---

.github/workflows/publish.yml
modules/map_app/templates/index.html
modules/map_app/views.py

fixes 
#79 #80 #81 #82
- remove unused and untrusted javascript library proj4
- pin pypa action version
- reduces exception information printed in log messages

Security fixes

---

modules/data_processing/forcings.py
modules/data_processing/zarr_utils.py

added annotations and docstrings to some functions in forcings.py and zarr_utils.py

Added annotations and docstrings to some functions 

---

modules/data_sources/source_validation.py
pyproject.toml

The download is slightly faster, the code is a bit more comprehensible, the biggest difference is not using the fake progress bar that would hang at 100% while decompression was happening which made it look like it was broken.

update to use boto3 for download

---

modules/data_processing/create_realization.py
modules/ngiab_data_cli/__main__.py

If a gage id is being used with the tool, check the s3 bucket for a calibrated parameter set for that gage. If one exists, use it, if not stick with the default method.
Most gages are not calibrated currently. ~1/18000 
https://communityhydrofabric.s3.us-east-1.amazonaws.com/index.html#hydrofabrics/community/gage_parameters/

automatically download best model parameters if available

---

modules/data_processing/datasets.py

Hi Josh 
I added the part to get the SWE data for NWM v.3.0 predictions. Please take a look at them and, if they are correct, accept the request. 
I just added the SWE based on your previous changes and tried not to make substantial changes to the code.

Added the SWE results of the NWM

---

modules/data_processing/create_realization.py
modules/data_processing/dataset_utils.py
modules/data_processing/datasets.py
modules/data_processing/file_paths.py
modules/data_processing/forcings.py
modules/data_processing/gpkg_utils.py
modules/data_processing/graph_utils.py
modules/data_processing/subset.py
modules/data_sources/source_validation.py
modules/map_app/__main__.py
modules/map_app/views.py
modules/ngiab_data_cli/__main__.py

Improve readability and long term maintainability by extending and correcting the type-annotation coverage.
As suggested, nullable arguments are marked with `Optional[{type}] = None` while 'nullable returns' types use `-> {type} | None:`.
I attempted to make all changes without affecting functionality or control flow as to prevent introducing any new issues.
As such, a few function calls and arguments are marked with `#type: ignore` rather than adding the if-else and other control blocks that would have been necessary to 'properly' fix.
Please point out spots I missed.

Improving Type Annotations

---

modules/data_processing/graph_utils.py
modules/data_processing/subset.py
modules/map_app/static/js/data_processing.js
modules/map_app/static/js/main.js
modules/map_app/views.py

see issue #123 
The CLI and map app both warn user before trying to overwrite a subset gpkg.

displays warning prompt when attempting to overwrite subset gpkg

---

modules/map_app/static/css/toggle.css
modules/map_app/static/js/data_processing.js
modules/map_app/static/js/main.js
modules/map_app/templates/index.html
modules/map_app/views.py

Addressing issue #148 
Keeping this a draft PR for now, because even though the first weird geometry was fixed:
More strange geometries have appeared:
So I guess I'll make a toggle feature and add that to this pr later

made map preview reflect actual subset area
